pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                echo 'Code Ready'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
                bat 'pip install flask'
            }
        }

        stage('Deploy Flask') {
            steps {
                bat 'pm2 restart flask-app'
            }
        }

        stage('Deploy Express') {
            steps {
                bat 'pm2 restart express-app'
            }
        }

    }
}
